dput-pgdg: handle failure explicitly

diff --git a/jenkins/dput-pgdg b/jenkins/dput-pgdg
--- a/jenkins/dput-pgdg
+++ b/jenkins/dput-pgdg
@@ -30,11 +30,11 @@ dcmd chmod a+r $CHANGES
 
 # upload packages
 dcmd rsync -av $CHANGES $HOST:/srv/apt/$QUEUE
-rm -rf *
 
 [ "$QUEUE" = "incoming" ] || exit 0
 
-# if processincoming fails, move files to "failed" directory
-trap "ssh $HOST mv /srv/apt/incoming/* /srv/apt/failed" 0 2 3 15
 # call processincoming once for all packages uploaded
-ssh $HOST sudo -u aptuser /srv/apt/apt.postgresql.org/repo/processincoming $QUEUE
+if ! ssh $HOST sudo -u aptuser /srv/apt/apt.postgresql.org/repo/processincoming $QUEUE; then
+	# if processincoming fails, move files to "failed" directory
+	ssh $HOST mv /srv/apt/$QUEUE/* /srv/apt/failed
+fi
